# Generated by Django 4.2.5 on 2023-10-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0003_student_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="portfolio",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio_app.portfolio",
            ),
        ),
    ]
