# Generated by Django 4.2.5 on 2023-10-10 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0005_project_portfolio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="portfolio_app.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="portfolio",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio_app.portfolio",
            ),
            preserve_default=False,
        ),
    ]
