# Generated by Django 4.2.5 on 2023-10-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio_app", "0013_themechanger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="is_active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="project", name="discription", field=models.TextField(null=True),
        ),
    ]
